apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: kube-vip
          env:
            - name: address
              value: "192.168.0.9"
